package com.agentflow.common.trace;

public enum TraceStage {
    SUBMITTED, DECOMPOSED, DISPATCHED, WORKER_RECEIVED, PROCESSED, RESULT_SENT,
    SUBTASK_SETTLED, RETRY, DLQ, RECOVERED, TIMEOUT_REDISPATCH, TASK_FINALIZED
}
